import * as THREE from "three";
import { GLTFExporter } from "three/examples/jsm/exporters/GLTFExporter.js"; // Correct import

export const exportToGLB = async (
  currentMesh,
  currentShapeName,
  onProgress
) => {
  if (!currentMesh) {
    console.error("No mesh to export for GLB.");
    onProgress(0);
    return null;
  }

  onProgress(10); // Initial progress

  const exporter = new GLTFExporter();
  const options = {
    binary: true, // Export as GLB
    trs: false, // बताता है कि क्या नोड ट्रांसफ़ॉर्मेशन शामिल करना है (आमतौर पर सत्य)
    onlyVisible: true, // केवल दृश्यमान ऑब्जेक्ट निर्यात करें
    truncateDrawRange: true, // यदि ड्रॉ रेंज का उपयोग किया जाता है तो बफ़र को छोटा करें
    // animations: currentMesh.animations || [], // अपनी एनिमेशन शामिल करें यदि आपके मेश में वे हैं
    // geoetry: true, // डिफ़ॉल्ट रूप से सत्य
  };

  return new Promise((resolve, reject) => {
    // GLTFExporter.parse is synchronous in its core logic for generating the structure,
    // but the data saving (to ArrayBuffer for GLB) is wrapped in a callback.
    // The progress simulation here is more about user feedback during this process.

    let simulatedProgress = 20;
    const progressInterval = setInterval(() => {
      simulatedProgress += 15;
      if (simulatedProgress <= 90) {
        onProgress(simulatedProgress);
      } else {
        clearInterval(progressInterval);
      }
    }, 100);

    try {
      exporter.parse(
        currentMesh, // The object(s) to export. Can be a scene, an array of objects, or a single object.
        (gltf) => {
          // gltf is the ArrayBuffer for GLB, or JSON object for glTF
          clearInterval(progressInterval);
          onProgress(100);
          resolve({
            glbBuffer: gltf,
            filename: `${currentShapeName}_3d_model.glb`,
          });
        },
        (error) => {
          clearInterval(progressInterval);
          console.error("An error happened during GLTF export:", error);
          onProgress(0);
          reject(error);
        },
        options
      );
    } catch (error) {
      clearInterval(progressInterval);
      console.error("Error setting up GLTFExporter:", error);
      onProgress(0);
      reject(error);
    }
  });
};

export const exportToOBJ = (currentMesh, currentShapeName) => {
  if (!currentMesh) {
    console.error("No mesh to export for OBJ.");
    return null; // Return null or an object indicating failure
  }
  // For actual OBJ export, you would use THREE.OBJExporter:
  // import { OBJExporter } from 'three/examples/jsm/exporters/OBJExporter.js';
  // const exporter = new OBJExporter();
  // const objContent = exporter.parse(currentMesh);

  // Using your provided manual OBJ generation as a fallback if OBJExporter is not used:
  const geometry = currentMesh.geometry;
  if (!geometry || !geometry.isBufferGeometry) {
    console.error("Mesh geometry is not BufferGeometry for OBJ export.");
    return null;
  }
  const positions = geometry.attributes.position
    ? geometry.attributes.position.array
    : null;
  if (!positions) {
    console.error("Mesh has no position attribute for OBJ export.");
    return null;
  }

  const normals = geometry.attributes.normal
    ? geometry.attributes.normal.array
    : null;
  const uvs = geometry.attributes.uv ? geometry.attributes.uv.array : null;
  const indices = geometry.index ? geometry.index.array : null;

  let objContent = `# ${currentShapeName.toUpperCase()} 3D Model\n`;
  objContent += `# Generated by Enhanced 3D Shapes\n`;
  objContent += `# Vertices: ${positions.length / 3}\n`;
  if (indices) objContent += `# Faces: ${indices.length / 3}\n\n`;
  else objContent += `# Faces: ${positions.length / 9}\n\n`; // For non-indexed
  objContent += `o ${currentShapeName}\n\n`;

  for (let i = 0; i < positions.length; i += 3) {
    objContent += `v ${positions[i].toFixed(6)} ${positions[i + 1].toFixed(
      6
    )} ${positions[i + 2].toFixed(6)}\n`;
  }
  if (uvs) {
    objContent += "\n";
    for (let i = 0; i < uvs.length; i += 2) {
      objContent += `vt ${uvs[i].toFixed(6)} ${uvs[i + 1].toFixed(6)}\n`;
    }
  }
  if (normals) {
    objContent += "\n";
    for (let i = 0; i < normals.length; i += 3) {
      objContent += `vn ${normals[i].toFixed(6)} ${normals[i + 1].toFixed(
        6
      )} ${normals[i + 2].toFixed(6)}\n`;
    }
  }
  objContent += "\n";
  if (indices) {
    for (let i = 0; i < indices.length; i += 3) {
      const v1 = indices[i] + 1,
        v2 = indices[i + 1] + 1,
        v3 = indices[i + 2] + 1;
      if (uvs && normals)
        objContent += `f ${v1}/${v1}/${v1} ${v2}/${v2}/${v2} ${v3}/${v3}/${v3}\n`;
      else if (normals)
        objContent += `f ${v1}//${v1} ${v2}//${v2} ${v3}//${v3}\n`;
      else if (uvs) objContent += `f ${v1}/${v1} ${v2}/${v2} ${v3}/${v3}\n`;
      else objContent += `f ${v1} ${v2} ${v3}\n`;
    }
  } else {
    // Non-indexed geometry
    for (let i = 0; i < positions.length / 9; i++) {
      const base = i * 3 + 1;
      const v1 = base,
        v2 = base + 1,
        v3 = base + 2;
      if (uvs && normals)
        objContent += `f ${v1}/${v1}/${v1} ${v2}/${v2}/${v2} ${v3}/${v3}/${v3}\n`;
      else if (normals)
        objContent += `f ${v1}//${v1} ${v2}//${v2} ${v3}//${v3}\n`;
      else if (uvs) objContent += `f ${v1}/${v1} ${v2}/${v2} ${v3}/${v3}\n`;
      else objContent += `f ${v1} ${v2} ${v3}\n`;
    }
  }
  return { objContent, filename: `${currentShapeName}_3d_model.obj` };
};

export const takeScreenshot = (renderer, shapeName) => {
  if (!renderer || !renderer.domElement) {
    console.error("Renderer not available for screenshot.");
    return null;
  }
  const canvas = renderer.domElement;
  try {
    const dataURL = canvas.toDataURL("image/png");
    return { dataURL, filename: `${shapeName}_screenshot.png` };
  } catch (error) {
    console.error("Error taking screenshot:", error);
    // This can happen if the canvas is tainted (e.g., cross-origin images without CORS)
    // or if preserveDrawingBuffer is false and a frame hasn't been rendered recently.
    return null;
  }
};
